### ISSUE TITLE
Left-align variants and match alleles to reference

### ISSUE THREAD

**Issue by juhis** [FINNGEN/META_ANALYSIS#14]
Analyzing variants from different studies causes output variants to be inconsistent for different phenotypes as a variant and its alleles in the output is now based on the first given study that has the variant for a phenotype.

say for pheno1 study1 has variant1 A G and study2 has G A -> will be A G in the output
but for pheno2 study1 has no variant1 and study2 has G A -> will be G A in the output

Also differently aligned variants are considered different variants currently.

Create an option to munge summary stats to have them consistent up front:
- left-align variants
- match alleles based on a given reference and flip betas when necessary

The munging should be separate from the meta program itself.

**Comment by Fedja** [comment]
This is handled in the preprocessing pipeline now
