### ISSUE TITLE
biobanks meta GWAS data sharing 

### ISSUE THREAD

**Issue by montenegrina** [FINNGEN/META_ANALYSIS#34]
Hello,

I plant to do meta GWAS of 3 large biobanks: Finngen, UKBiobank, Biobank Japan. Can you please tell me does Finngen has constrains/recommendations as to where that meta gwas summary statistics can be publicly shared?

Thanks
Ana

**Comment by juhaa** [comment]
There's no constraints to publicly released FinnGen summary statistics. We kindly ask to acknowledge FinnGen if publishing results using the FinnGen summary statistics. See more details here https://finngen.gitbook.io/documentation/how-to-cite
