### ISSUE TITLE
Harmonization messes up column ordering

### ISSUE THREAD

**Issue by juhaa** [FINNGEN/META_ANALYSIS#39]
Harmonization script messes up column ordering for `extra_cols`:
https://github.com/FINNGEN/META_ANALYSIS/blob/a252f8497775b160cb8ebacbf2ca44a00a93a0ff/scripts/harmonize.py#L150-L153
Probably fixed by changing to `OrderedDict`

**Comment by juhaa** [comment]
...or just update Python in docker to 3.7+ where dicts are ordered

**Comment by Fedja** [comment]
if the idea here is to have all other than required columns spit out after the required columns in otherwise original order then just don't use the h_idx in the list comprehension but just the list you get after header line split()

**Comment by juhaa** [comment]
> if the idea here is to have all other than required columns spit out after the required columns in otherwise original order then just don't use the h_idx in the list comprehension but just the list you get after header line split()

Or that yes.
