### ISSUE TITLE
Does not align to all references in the same position

### ISSUE THREAD

**Issue by Fedja** [FINNGEN/META_ANALYSIS#50]
In here the ref var array is emptied although current variant could be in the same position as the last processed variant. 
Need to empty the ref array only if position has surpassed those in the ref array (in case which new variants should not be read into the ref array)
https://github.com/FINNGEN/META_ANALYSIS/blob/9faf18a4f1762326bb92e724c869eb0641f5f8c1/scripts/harmonize.py#L160

**Comment by juhaa** [comment]
Already fixed but seems I only updated it in the wdl 1.0 branch:

https://github.com/FINNGEN/META_ANALYSIS/blob/34888784e742a57f298bad7e21eeb41000aba21d/scripts/harmonize.py#L199-L200

I've been using the wdl 1.0 branch for all the runs recently so they should be fine. There's a PR (#47)  up about it if we are ready to take the leap to 1.0...

**Comment by juhaa** [comment]
Took the leap to wdl 1.0 and merged #47
